
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/efecampanas
spring.datasource.username=postgres
spring.datasource.password=Cerdito2025
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
gemini.api.key=AIzaSyAbdB_SzuSw61wviGYU4o9R0W1iZfPJosA
spring.web.resources.static-locations=classpath:/static/,file:landings/
meta.whatsapp.token=EAALcxf2qvM8BRL4u8SpQPr8bRTm1gwBfk0MXC84DnhmMt3W1hCmUnfdzJZB5zVLA7UrR9ZAHD9R3xG1BXqzBZBwuTh0kN6PLasQRXCrKh1VoZCLtDbZC8E7RSdslZBnI1yqKIsgXMplGKmMBlnWiD7qH6WLAvPcjLa1tVmPibg67lDXqhMc7EXqVisc2DgITTAvQZDZD

# Configuración del servidor SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=javadesarolladorjva@gmail.com
spring.mail.password=dnvvzqvfzjvbubdb

# Propiedades adicionales
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true